test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

<% if ENV["AWS_ACCESS_KEY_ID"].present? %>
amazon:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV.fetch("AWS_REGION", "us-east-1") %>
  bucket: <%= ENV.fetch("AWS_BUCKET", "prose-uploads") %>
  <% if ENV["AWS_ENDPOINT"].present? %>
  endpoint: <%= ENV["AWS_ENDPOINT"] %>
  force_path_style: true
  <% end %>
<% end %>
